name: EmbroideryStudio
options:
  bundleIdPrefix: com.embroidery
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    ENABLE_HARDENED_RUNTIME: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES

targets:
  EmbroideryStudio:
    type: application
    platform: macOS
    sources:
      - path: Sources
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.embroidery.studio
        PRODUCT_NAME: EmbroideryStudio
        INFOPLIST_FILE: Sources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sources/EmbroideryStudio.entitlements
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: NO
    dependencies:
      - framework: SwiftUI.framework
        embed: false
      - framework: AppKit.framework
        embed: false
      - framework: Metal.framework
        embed: false
      - framework: MetalKit.framework
        embed: false
      - framework: UniformTypeIdentifiers.framework
        embed: false
    preBuildScripts:
      - script: |
          echo "Building EmbroideryStudio v${MARKETING_VERSION}"
        name: "Build Info"
